POST http://localhost:3001/api/blogposts/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN0YW43OCIsImlkIjoiNWRlZTNlYzUwYTdmNTVkNDVkMjAwZTYyIiwiaWF0IjoxNTc1OTE1MDMzfQ.Tgg_HS7Dh3CL69QdRxs2GNKYX51hL4ZPK97uaxn2iR8

{ 
    "title":"blah blah blah blah",
    "author":"meh",
    "url":"www.bleh.com",
    "userId":"5dee3ec50a7f55d45d200e62"
}